apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: {{ .Values.namespace }}
  name: {{ .Values.namespace }}
---

#apiVersion: v1
#kind: ConfigMap
#metadata:
  #name: {{ .Values.name }}-configmap
  #namespace: {{ .Values.namespace }}
#data:
  #myvalue: "Hello World"
